spring.application.name=order-service
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/YandexMarketDB}
spring.datasource.username=${DB_USER:Viar}
spring.datasource.password=${DB_PASSWORD:12345}
spring.jpa.hibernate.ddl-auto=none
spring.kafka.consumer.group-id=order-service-group
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
server.port=8082
payment-service.base-url=${PAYMENT_SERVICE_BASE_URL:http://localhost:8081}
order-paid-topic=orders.events
delivery-assigned-topic=delivery.events
